baseURL = 'https://awainverse.github.io/hugo-quickstart'
languageCode = 'en-us'
title = 'Aaron Anderson'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"